from datetime import datetime

import httpx
import pytest

from app.schemas.users import UserCreate, UserRead, UserUpdate
from tests.utils import log, logjson


@pytest.mark.asyncio
async def test_users_add(add_test_users: list[dict], users_url):
    # Validate created test users
    user_req_fields = UserCreate.model_validate(add_test_users[0])
    user_all_fields = UserCreate.model_validate(add_test_users[1])

    async with httpx.AsyncClient() as client:
        # Get test users from db
        resp = await client.get(users_url)
        respbody = resp.json()
        logjson("Got users:", respbody)

        db_user_req_fields = next(
            (user for user in respbody if user.get("username") == user_req_fields.username), 
            None
        )
        assert db_user_req_fields is not None, "Test user not found (possible error during creating)"
        db_user_all_fields = next(
            (user for user in respbody if user.get("username") == user_all_fields.username), 
            None
        )
        assert db_user_all_fields is not None, "Test user not found (possible error during creating)"

        # Validate test users got from db
        db_user_req_fields_model = UserRead.model_validate(db_user_req_fields)
        db_user_all_fields_model = UserRead.model_validate(db_user_all_fields)

        # Verify that the users stored in the database match the values defined during test setup
        # ID is excluded because it is auto-generated by the database
        assert db_user_req_fields_model.model_dump(exclude={"id"}) == user_req_fields.model_dump()
        assert db_user_all_fields_model.model_dump(exclude={"id"}) == user_all_fields.model_dump()


@pytest.mark.asyncio
async def test_users_add_wo_username(add_test_users: list[dict], users_url):
    async with httpx.AsyncClient(base_url=users_url) as client:
        r = await client.post("/", json={"username": None})
        assert r.status_code == httpx.codes.UNPROCESSABLE_ENTITY

        rbody = r.json()
        detail = rbody["detail"][0]

        assert detail["loc"] == ["body", "username"]
        assert detail["msg"] == "Input should be a valid string"


@pytest.mark.asyncio
async def test_users_get(add_test_users: list[dict], users_url):
    async with httpx.AsyncClient() as client:
        created_user_req_fields = add_test_users[0]
        created_user_all_fields = add_test_users[1]

        resp = await client.get(users_url)
        respbody = resp.json()
        logjson("Got users:", respbody)

        # Search test users in the response by username
        user_with_req_fields_dict = next(
            (user for user in respbody if user.get("username") == created_user_req_fields.get("username")), None
        )
        assert user_with_req_fields_dict is not None, "Test user not found (possible error during creating)"
        user_with_all_fields_dict = next(
            (user for user in respbody if user.get("username") == created_user_all_fields.get("username")), None
        )
        assert user_with_all_fields_dict is not None, "Test user not found (possible error during creating)"

        test_user_with_req_fields = UserRead.model_validate(user_with_req_fields_dict)
        test_user_with_all_fields = UserRead.model_validate(user_with_all_fields_dict)

        assert resp.status_code == httpx.codes.OK
        assert created_user_req_fields == test_user_with_req_fields.model_dump(exclude={"id"})
        assert created_user_all_fields == test_user_with_all_fields.model_dump(exclude={"id"})


@pytest.mark.asyncio
async def test_user_get_by_id(add_test_users: list[dict], users_url):
    user_req_fields = add_test_users[0]

    async with httpx.AsyncClient(base_url=users_url) as client:
        r = await client.get("/")
        rbody = r.json()

        test_user_id = next(
            (user.get("id") for user in rbody if user.get("username") == user_req_fields.get("username")),
            None
        )
        assert test_user_id is not None, "Test user not found (possible error during creating)"

        rbyid = await client.get(f"/{test_user_id}")
        assert rbyid.status_code == httpx.codes.OK

        rbyidbody = rbyid.json()
        db_test_user = UserRead.model_validate(rbyidbody)
        assert db_test_user.model_dump(exclude={"id"}) == user_req_fields


@pytest.mark.asyncio
async def test_users_update(add_test_users: list[dict], users_url):
    async with httpx.AsyncClient(base_url=users_url) as client:
        user_req_fields_updated = UserUpdate(
            name="TestUserNameUpd",
            surname=f"TestUserSurnameUpd",
            username=f"TestUserAllFieldsUpd_{datetime.now().strftime('%Y%m%d-%H%M%S.%f')[:-3]}",
            comment="User for testing updated",
            role="user"
        )

        user_all_fields_updated = UserUpdate(
            role="test"
        )

        created_user_req_fields = add_test_users[0]
        created_user_all_fields = add_test_users[1]


        resp = await client.get(users_url)
        respbody = resp.json()
        logjson("Got users:", respbody)

        user_with_req_fields_dict: dict = next(
            user for user in respbody if user.get("username") == created_user_req_fields.get("username")
        )
        user_with_all_fields_dict: dict = next(
            user for user in respbody if user.get("username") == created_user_all_fields.get("username")
        )
        id_user_req_fields = user_with_req_fields_dict.get("id")
        id_user_all_fields = user_with_all_fields_dict.get("id")
        log.info(f"Got users IDs: {id_user_req_fields}, {id_user_all_fields}")

        # Update all fields
        resp_upd_req = await client.put(f"/{id_user_req_fields}", json=user_req_fields_updated.model_dump())
        resp_upd_req_body = resp_upd_req.json()
        resp_upd_req_model = UserUpdate.model_validate(resp_upd_req_body)

        assert resp_upd_req_model.model_dump() == user_req_fields_updated.model_dump()

        # Update only one field
        resp_get_test_user = await client.get(f"/{id_user_all_fields}")
        resp_test_user_body = resp_get_test_user.json()
        resp_test_user_body_model = UserRead.model_validate(resp_test_user_body)
        resp_test_user_body_model_updated = resp_test_user_body_model.model_copy(update={"role": "test"})
        
        resp_upd_all = await client.put(
            f"/{id_user_all_fields}", 
            json=user_all_fields_updated.model_dump(exclude_unset=True)
        )
        resp_upd_all_body = resp_upd_all.json()
        resp_upd_all_model = UserUpdate.model_validate(resp_upd_all_body)

        assert resp.status_code == httpx.codes.OK
        assert resp_upd_all_model.model_dump() == resp_test_user_body_model_updated.model_dump(exclude={"id"})


@pytest.mark.asyncio
async def test_user_delete(users_url):
    test_user = UserCreate(
        username=f"TestUserRequiredFields_{datetime.now().strftime('%Y%m%d-%H%M%S.%f')[:-3]}"
    )

    async with httpx.AsyncClient(base_url=users_url) as client:
        rpost = await client.post("/", json=test_user.model_dump())
        assert rpost.status_code == httpx.codes.CREATED

        rget = await client.get("/")
        assert rget.status_code == httpx.codes.OK
        rgetbody = rget.json()

        user_id = next(
            (user.get("id") for user in rgetbody if user.get("username") == test_user.username),
            None
        )
        assert user_id is not None, f"User with username {test_user.username} not found"

        rdel = await client.delete(f"/{user_id}")
        assert rdel.status_code == httpx.codes.OK

        rgetbyid = await client.get(f"/{user_id}")
        rgetbyid_body = rgetbyid.json()

        assert rgetbyid.status_code == httpx.codes.NOT_FOUND
        assert rgetbyid_body == {"detail": "User with provided ID is not found"}
